# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: centos:centos7
  steps:
    - echo: echo "Hello world"

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main1:
    requires: [ ~commit ]

  main2:
    requires: [ ~pr ]

  main3:
    requires: [ ~main1 ]

  main4:
    requires: [ ~main2 ]
