# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: centos:centos7
  steps:
    - echo: echo "Hello world"

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    requires: [ ~commit, ~pr ]
    environment:
      GIT_SPARSE_CHECKOUT_PATH: "sample"
    steps:
      - echo: |
          echo "GIT_SPARSE_CHECKOUT_PATH=${GIT_SPARSE_CHECKOUT_PATH}"
          pwd
          ls -la
          ls -la test || true
