# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: centos:centos7

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
      - rm: rm -R $SD_ARTIFACTS_DIR
