# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
childPipelines:
  scmUrls:
    - git@github.com:yakanechi/screwdriver-oss-test-external-child1.git
    # - git@github.com:yakanechi/screwdriver-oss-test-external-child2.git

shared:
  image: centos:centos7
  steps:
    - echo: echo "Hello world"

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    requires: [ ~commit, ~pr ]
