# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
# childPipelines:
#   scmUrls:
#     - git@github.com:yakanechi/screwdriver-oss-test-child.git

shared:
  image: centos:centos7
  steps:
    - echo: echo "Hello world"

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    requires: [ ~commit, ~pr ]
