parameters:
  region:
    value: "kks"
    description: "Region setting"
  cluster: ["cluster1", "cluster2"]

# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: centos:centos7
  steps:
    - echo: echo "Hello world"

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    parameters:
      param1: "foo"
    requires: [ ~commit, ~pr ]
