# ----------------------------------------------------------------------------------------------------------------------
# 
#     shared
# 
# ----------------------------------------------------------------------------------------------------------------------
shared:
  image: centos:centos7

# ----------------------------------------------------------------------------------------------------------------------
# 
#     jobs
# 
# ----------------------------------------------------------------------------------------------------------------------
jobs:
  main:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - echo "Hello, normal job"
